### PR TITLE
Update pulsechain metadata

### PR DESCRIPTION
**Pull request by 3commascapital**
## Description

Update metadata for pulsechain networks

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:

### CODE REVIEW

**Comment by 3commascapital** [comment]
seems there was a recent issue with a token: ```
Run actions/checkout@v3
Error: Input required and not supplied: token
```

**Review by tmm — COMMENTED** [review]
Please add a changeset with `pnpm changeset`.

**Comment by 3commascapital** [comment]
token issue remains @tmm

**Comment by 3commascapital** [comment]
seems like a lot of people are hitting this token issue @tmm

**Review by tmm — APPROVED** [review]

**Pull request merged**
