### PR TITLE
Add Frame connector

### PR DESCRIPTION
**Pull request by goosewobbler**
## Description

New connector for [Frame](https://frame.sh) - Uses injected provider if available, otherwise connects using `eth-provider`.

Connector request: https://github.com/wagmi-dev/references/discussions/265
Main repo PR: https://github.com/wagmi-dev/wagmi/pull/2296

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

### CODE REVIEW

**Comment by salil-naik** [comment]
Hey @goosewobbler, is anything pending or missing in this PR? Was wondering why it's not yet merged.

**Comment by goosewobbler** [comment]
@salil-naik Nothing missing as far as I can tell. I'm still awaiting feedback or merge from a maintainer. I don't actually work for Frame any more but happy to push this through as the likely alternative is that it will be abandoned.

**Comment by dirtycajunrice** [comment]
> @salil-naik Nothing missing as far as I can tell. I'm still awaiting feedback or merge from a maintainer. I don't actually work for Frame any more but happy to push this through as the likely alternative is that it will be abandoned.

@goosewobbler If you would like to give me access to this fork, i would like to clean up the failing checks and the injection logic to get this PR to merge-able

**Comment by goosewobbler** [comment]
@dirtycajunrice added

**Comment by tmm** [comment]
Appreciate the effort that went into this! We've been busy with other work so haven't had time to support new connectors. We are reworking how connectors are setup (directly in the wagmi repo instead of references, new API, etc.) so once that is done this can be created again. Stayed tuned to the [wagmi discussion board](https://github.com/wagmi-dev/wagmi/discussions) for more info.

**Pull request closed without merging**
