### PR TITLE
fix remove tokenpocket wallet login limit

### PR DESCRIPTION
**Pull request by chendatony31**
## Description

Remove TokenPocket's limitation, as every injected wallet has implemented the same interface, it's not fair just to add some of them. And most dapp only add metamask's provider, which causes the dapp cannot log in with our wallet.

## Additional Information

- [x] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:
tonychen.eth

### CODE REVIEW

**Comment by jxom** [comment]
This is the MetaMask Connector. It should only target the MetaMask extension. 

Consumers should be using the Injected Connector to target other wallets.

**Comment by jxom** [comment]
Might be worth getting in touch with the dapps and asking them to support other wallets apart from MetaMask.

**Comment by chendatony31** [comment]
> So I think is ok for me to add every other wallet flag in the injected wallet to make sure it is the true metamask right?

**Comment by chendatony31** [comment]
Ok, I've opened another PR https://github.com/wagmi-dev/references/pull/228 and will consider implementing EIP-5749.

**Pull request closed without merging**
