### PR TITLE
Add Luniverse chain

### PR DESCRIPTION
**Pull request by siosio34**
## Description

Add Luniverse chain.

## Additional Information

> [O] I read the [contributing docs](/wagmi-dev/references/blob/main/.github/CONTRIBUTING.md) (if this is your first contribution)

Your ENS/address:

### CODE REVIEW

**Comment by jxom** [comment]
Is this a valid chain? Seems like it is not on chainlist.org: https://chainlist.org/chain/256

**Comment by siosio34** [comment]
@jxom 

hello. If you are asking if the current chain is a valid chain, yes. Currently, the NFTs minted to the chain from the site below are being traded on the exchange.

https://upbit.com/nft/

However, as you said, the chain is not registered on chainlist.org. Is it necessary to register the chain on the site first to be used in wagmi?

**Comment by jxom** [comment]
Seems like the chain id is already taken: https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-256.json

Any idea?

**Comment by siosio34** [comment]
Our project has distributed quite a lot of NFTs in Korea, and now replacing the chain ID is not a small task.

However, if the principle is that only chains registered on https://chainlist.org are registered in the references package, I think this pull request should be closed.

However, it seems that the chain in the https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-256.json link is not being used well and is not registered in wagmi.

our chain is used to trade quite a lot of NFTs in Korea, even though it is not registered on the chainlist.

So, I would really appreciate it if you would consider registering the chain once again.

**Comment by tmm** [comment]
Chains should now be edited/added on the [Viem repository](https://github.com/wagmi-dev/viem).

**Pull request closed without merging**
