### PR TITLE
feat : add support for opBNB Testnet chain 🚀

### PR DESCRIPTION
**Pull request by karangoraniya**
feat: add support for opBNB Testnet chain 🚀

## Description

- **Network Name**: opBNB Testnet
- **New RPC URL**: https://opbnb-testnet-rpc.bnbchain.org/
- **ChainID**: 5611
- **Symbol**: tBNB
- **Explorer**: http://opbnbscan.com/

## Additional Information

The opBNB network is the Layer 2 scaling solution for the BNB Smart Chain powered by [bedrock version](https://community.optimism.io/docs/developers/bedrock/) of Optimism OP Stack.

- Note: Regarding the multicall3 contract address, I've created an [Deployment Request](https://github.com/mds1/multicall/issues/137) for its deployment. Once the deployment is complete, I will update the contract address.

Your ENS/address: karangoraniya.eth

### CODE REVIEW

**Comment by jxom** [comment]
Chain doesn't seem to exist: https://chainlist.org/chain/5611

**Comment by karangorania** [comment]
> Chain doesn't seem to exist: https://chainlist.org/chain/5611

Everything is not present on https://chainlist.org/. You can check the official site; it's from BNB Chain.

Here are some references that might be helpful.

Additionally, note that it's built upon the OP stack by Optimism.

[OPBNB Bridge](https://opbnb-testnet-bridge.bnbchain.org/deposit)
[Official Site](https://opbnb.bnbchain.org/en)
[Discord](https://discord.com/invite/bnbchain)
[Official Tweet From Binance](https://twitter.com/BNBCHAIN/status/1679491954449731587?s=20)
[bnbchainlist](https://www.bnbchainlist.org/)

**Comment by jxom** [comment]
In order for this chain to be approved, we will need it listed on https://github.com/ethereum-lists/chains/tree/master/_data/chains to avoid chain conflicts, etc

**Comment by karangorania** [comment]
Ok, Do I have to create the PR, or will you list the chain there?

**Comment by jxom** [comment]
Closing for now. Please re-open when the chain has been merged into ethereum-chains though!

**Comment by karangoraniya** [comment]
okay

**Pull request closed without merging**
